language: cpp

before_install:
    - sudo apt-get install -qq libqt4-core libqt4-dev libqt4-gui qt4-dev-tools libssl-dev

script:
    - mkdir build
    - cd build
    - qmake ../*.pro
    - make
    - sudo make install
